app/__init__.py
from flask import Flask
import os
import ConfigParser
from logging.handlers import RotatingFileHandler
from flask.ext.pymongo import PyMongo
from flask.ext.cors import CORS
from app.utils.mongo_utils import MongoUtils

# Create MongoDB database object.
mongo = PyMongo()

#Initialize mongo access point
mongo_utils = MongoUtils(mongo)

def create_app():
    # Here we  create flask instance
    app = Flask(__name__)

    # Allow cross-domain access to API.
    #cors = CORS(app, resources={r"/api/*": {"origins": "*"}})

    # Load application configurations
    load_config(app)

    # Configure logging.
    configure_logging(app)

    # Init modules
    init_modules(app)

    # Initialize the app to work with MongoDB
    mongo.init_app(app, config_prefix='MONGO')

    return app


def load_config(app):
    ''' Reads the config file and loads configuration properties into the Flask app.
    :param app: The Flask app object.
    '''
    # Get the path to the application directory, that's where the config file resides.
    par_dir = os.path.join(__file__, os.pardir)
    par_dir_abs_path = os.path.abspath(par_dir)
    app_dir = os.path.dirname(par_dir_abs_path)

    # Read config file
    config = ConfigParser.RawConfigParser()
    config_filepath = app_dir + '/config.cfg'
    config.read(config_filepath)

    app.config['SERVER_PORT'] = config.get('Application', 'SERVER_PORT')
    app.config['MONGO_DBNAME'] = config.get('Mongo', 'DB_NAME')

    # Logging path might be relative or starts from the root.
    # If it's relative then be sure to prepend the path with the application's root directory path.
    log_path = config.get('Logging', 'PATH')
    if log_path.startswith('/'):
        app.config['LOG_PATH'] = log_path
    else:
        app.config['LOG_PATH'] = app_dir + '/' + log_path

    app.config['LOG_LEVEL'] = config.get('Logging', 'LEVEL').upper()


def configure_logging(app):
    ''' Configure the app's logging.
     param app: The Flask app object
    '''

    log_path = app.config['LOG_PATH']
    log_level = app.config['LOG_LEVEL']

    # If path directory doesn't exist, create it.
    log_dir = os.path.dirname(log_path)
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)

    # Create and register the log file handler.
    log_handler = RotatingFileHandler(log_path, maxBytes=250000, backupCount=5)
    log_handler.setLevel(log_level)
    app.logger.addHandler(log_handler)

    # First log informs where we are logging to.
    # Bit silly but serves  as a confirmation that logging works.
    app.logger.info('Logging to: %s', log_path)


def init_modules(app):

    # Import blueprint modules
    from app.mod_main.views import mod_main

    app.register_blueprint(mod_main)

app/mod_main/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import mongo
from bson import json_util, ObjectId

mod_main = Blueprint('main', __name__)

@mod_main.route('/', methods=['GET','POST'])
def index():
    db = mongo.db.arkep
    if request.method == 'GET':
        return render_template('index.html')
    elif request.method == 'POST':
        data = request.form.to_dict()
        db.insert(data)
        return redirect(url_for('.listo'))

@mod_main.route('/<string:id>', methods=['GET'])
def get_doc(id):
    db = mongo.db.arkep
    if request.method == 'GET':
        doc = db.find_one({"_id":ObjectId(id)})
        doc_json = json_util.dumps(doc)
        return render_template('doc.html', doc=doc)
    else:
        return "bad request"

@mod_main.route('/listo',methods=['GET'])
def listo():
    db = mongo.db.arkep
    myCursor = db.find();
    if request.method == 'GET':
        return render_template('list.html', myCursor=myCursor)

@mod_main.route('/delete_document<id>')
def delete_document(id):
    db = mongo.db.arkep
    db.remove({"_id":ObjectId(id)})
    return redirect(url_for('.listo'))

@mod_main.route('/arkep', methods=['GET','POST'])
def arkep():
    form = arkep()
    # TODO: render arkep.html
    # TODO: form.validate_on_submit()

app/templates/doc.html
{% extends 'layout.html' %}
{% block content %}
Rezultati i kerkuar:
{{ doc }}
{% endblock %}

app/templates/index.html
<head>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/jquery.validate.min.js"> </script>

  <script>
    $(document).ready(function() {
          $('#formular').validate({
              rules: {
                               entiteti: {
                  required: true
                },
                               numri_regjis: {
                  required: true,
                  number: true,
                  minlength: 7
                },
				fiskal: {
		 required: true,			
		 number: true
                },
				adresa: {
                 required: true
                },
				tel: {
                  required: true,
	          number: true
                },
				email: {
                  required: true
                },
				pershkrim: {
                  required: true
                },
              },
              messages: { entiteti: {
				required: "Ju lutem shkruani nje emer valid."
				},

		          numri_regjis: {
				required: "Ju lutem shkruani nje numer valid."
				},

                          fiskal: {
				required: "Ju lutem shkruani nje numer valid."
				},

			  adresa: {
				required: "Ju lutem shkruani nje adrese valide."
				},

			  tel: {
				required: "Ju lutem shkruani nje numer telefoni valid."
				},

		          email: {
				required: "Ju lutem shkruani nje email valide."
				},
			 
			  pershkrim: {
				required: "Ju lutem shkruani nje pershkrim valid."
				}
              }

            });

          });
  </script>
</head>
<body>
  <h1>FORMULAR I NJOFTIMIT</h1>
  <div class="info">
    <p> për <br>
      Hyrje në aktivitetin e Komunikimeve Elektronike
    </p>
  </div>
  <form  method="post" id="formular">
    <h3>Autoriteti do të procedoj me shqyrtimin e Formularit të Njoftimit vetëm pas kompletimit të Dosjes dhe do ta njoftoj ndërmarrësin për vendosjen në Regjistrin e Njoftimit brenda 5 (pesë) ditëve të punës nga data e kompletimit të Njoftimit.</h3>
    <div class="contentform">

      <div class="form-group">
        <!-- Part 1 starts-->
        <legend>
          <p> <span class="number"> I </span> QELLIMI I NJOFTIMIT <span>*</span></p>
        </legend>
        <select id="qellimi" name="qellimi_njoftimit" required>
          <option value="fillim_sherbimi">Fillimi i shërbimit</option>
          <option value="shtim_sherbimi"> Shtim shërbimi</option>
          <option value="heqje_sherbimi">Heqje shërbimi</option>
        </select>
      </div>
      <!-- Part 1 ends-->
      <div class="leftcontact">
        <!-- Part 2 starts-->
        <legend> <span class="number">II </span> TË DHËNAT PËR NDËRMARRËSIN:</legend>
        <div class="form-group">
          <label for="entiteti">
            <p>1.1. Emri i Ndërmarrësit (Entiteti)<span>*</span></p>
          </label>
          <span class="icon-case"></span>
          <input type="text" name="entiteti" id="entiteti" />
        </div>
        <!-- Part 2 ends-->
        <div class="form-group">
          <!-- Part 3 starts-->
          <p>1.2 Numri i Regjistrimit të Biznesit <span>*</span></p>
          <span class="icon-case"></span>
          <input type="text" name="numri_regjis" id="numri_regjis" />
       </div>
        <!-- Part 3 ends-->
        <div class="form-group">
          <!-- Part 4 starts-->
          <p>1.3 Numri fiskal<span>*</span></p>
          <span class="icon-case"></span>
          <input type="text" name="fiskal" id="fiskal" />
        </div>
        <!-- Part 4 ends-->
        <div class="form-group">
          <!-- Part 5 starts-->
          <p>1.4 Adresa <span>*</span></p>
          <span class="icon-case"></span>
          <input type="text" name="adresa" id="adresa" />
        </div>
        <!-- Part 5 ends-->
        <div class="form-group">
          <!-- Part 6 starts-->
          <p>1.5 Numri i Telefonit <span>*</span></p>
          <span class="icon-case"></span>
          <input type="text" name="tel" id="tel" />
        </div>
        <!-- Part 6 ends-->
        <div class="form-group">
          <!-- Part 7 starts-->
          <p>1.6 Numri i Faksit <span>*</span></p>
          <span class="icon-case"></span>
          <input type="text" name="fax" id="fax" />
        </div>
        <!-- Part 7 ends-->
        <div class="rightcontact">
          <!-- Part 8 starts-->
          <div class="form-group">
            <p>1.7 E-mail adresa <span>*</span></p>
            <span class="icon-case"></span>
            <input type="email" name="email" id="email" />
          </div>
          <!-- Part 8 ends-->
          <div class="form-group">
            <!-- Part 9 starts-->
            <legend> <span class="number">III </span> AKTIVITETET TË CILAT NJOFTOHEN/CREGJISTROHEN:</legend>
            <p>1. Ofrimi i rrjetit publik fiks <span>*</span></p>
            <select id="rrjeti" name="rrjeti_publik" required>
              <option value="lokal">Lokal</option>
              <option value="nacional">Nacional</option>
              <option value="tjera">Tjera(specifikoj)</option>
            </select>
          </div>
          <!-- Part 9 ends-->
          <div class="form-group">
            <!-- Part 10 starts-->
            <p>2. Ofrimi i shërbimeve publike fikse<span>*</span></p>
            <select id="sherbime" name="sherbime_publike" required>
              <option value="lokale_nacionale">Shërbime telefonike lokale/nacionale</option>
              <option value="nderkombetare">Shërbime telefonike ndërkombëtare</option>
              <option value="publik">Telefona publik me pagesë</option>
              <option value="sherbime_tjera">Shërbime tjera (specifikoj)</option>
            </select>
          </div>
        </div>
        <!-- Part 10 ends-->
        <div class="form-group">
          <!-- Part 11 starts-->
          <p>3. Ofrimi i rrjetit publik mobil
            <span>*</span>
          </p>
          <select id="rrjeti_publik" name="rrjeti_publik" required>
            <option value="rrjeti_lokal">Lokal</option>
            <option value="rrjeti_nacional">Nacional</option>
          </select>
        </div>
      </div>
      <!-- Part 11 ends-->
      <div class="form-group">
        <!-- Part 12 starts-->
        <legend><span class="number">IV</span> PËRSHKRIMI I AKTIVITETIT DHE FAZA E OFRIMIT:</legend>
        <p>Përshkrimi i rrjetit dhe/ose shërbimit që do të ofrohet:<span>*</span></p>
        <span class="icon-case"></span>
        <textarea name="pershkrim" rows="14"></textarea>
      </div>
      <!-- Part 12 ends-->
      <div class="form-group">
        <!-- Part 13 starts-->
        <legend>
          <p><span class="number">V</span> KONFIRMIMI I NJOFTIMIT:
            <span>*</span>
          </p>
        </legend>
        <p>Ndërmarrja kërkon që t’i lëshohet certifikata e konfirmimit të njoftimit për ofrimin e shërbimeve publike: </p>
        <select id="konfirmim" name="konfirmim" required>
          <option value="rrjeti_lokal">Po</option>
          <option value="rrjeti_nacional">Jo</option>
        </select>
      </div>
    </div>
    <!-- Part 13 ends-->
    </div>
    </div>
    <button type="submit" class="button-contact">Dergo</button>
  </form>
  <footer>
    <p> Adresa: Qyteza Pejton, Rr. Mujo Ulqinaku nr. 7, 10 000 Prishtinë, Republika e Kosovës <br>
      Tel: + 381 (38) 212-345; Fax: + 381 (38) 212 399; <br>
      E-mail: info@arkep-rks.org; web-site: www.arkep-rks.org
    <p>
  </footer>
</body>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<style>
th {
  color: #fff;;
  background:#81BDA4;
  font-size:23px;
  font-weight: 100;
  padding:24px;
  text-align:left;
  text-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  vertical-align:middle;
  font-family: 'Open Sans', sans-serif;
}

td {
  color: #666;
  background:#eaeaea;
  font-size:23px;
  font-weight: 100;
  padding:24px;
  text-align:left;
  text-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  vertical-align:middle;
  font-family: 'Open Sans', sans-serif;
}
</style>
	<title>Techstitution</title>
</head>
<body>
	{% block content %}

		{% endblock %}
</body>
</html>

app/templates/list.html
{% extends 'layout.html' %}
{% block header %}
  <h4 class="center-align" style="margin-bottom:30px">Ndermarresit</h4>
{% endblock %}
{% block content%}
<div class="card-panel">
  <table align="center" class="highlight bordered responsive-table" style="width: 100%;">
  <thead>
    <tr>
      <th>Emri i Ndermarresit</th>
      <th>Adresa</th>
      <th>Opsionet</th>
    </tr>
  </thead>
  <tbody>
  {% for record in myCursor %}
  <tr class="item-row">
    <td>
      {{ record['entiteti'] }}
    </td>
    <td>
      {{ record['adresa'] }}
    </td>
    <td>
      <a class="" href="{{url_for('main.get_doc',id=record._id)}}">View</a>/
      <a href="{{url_for('.delete_document', id=record._id)}}">Remove</a>
    </td>
  </tr>
  {%endfor%}
  </tbody>
  </table>
</div>
{% endblock %}